import type { AudioContinuityPlan, AudioTimelineV2, TimelineClock } from '@/lib/audio-design/types'

export const TEST_CLOCK: TimelineClock = {
  fpsNumerator: 24,
  fpsDenominator: 1,
  sampleRate: 48_000,
  totalFrames: 240,
}

export function createTestContinuityPlan(): AudioContinuityPlan {
  return {
    schemaVersion: 3,
    soundWorlds: [{
      worldId: 'stadium-world',
      continuityKey: 'stadium-same-night-same-storm',
      range: { startFrame: 0, endFrameExclusive: 240 },
      location: 'indoor stadium and its exterior entrance',
      timeContext: 'same night',
      weatherContext: 'same rainstorm',
      persistentSourceIds: ['stadium-crowd', 'storm-rain'],
      perspectives: [{
        perspectiveId: 'stadium-interior',
        zoneId: 'interior',
        range: { startFrame: 0, endFrameExclusive: 120 },
        enclosure: 'enclosed',
        distance: 'far',
        occlusion: 0.7,
        description: 'rain filtered by the stadium shell',
      }, {
        perspectiveId: 'stadium-exterior',
        zoneId: 'exterior',
        range: { startFrame: 120, endFrameExclusive: 240 },
        enclosure: 'open',
        distance: 'near',
        occlusion: 0.1,
        description: 'the same storm heard directly outdoors',
      }],
    }],
    acousticTransitions: [{
      transitionId: 'exit-stadium',
      sourceContinuityId: 'storm-rain',
      range: { startFrame: 108, endFrameExclusive: 132 },
      fromZoneId: 'interior',
      toZoneId: 'exterior',
      transitionType: 'exiting_enclosure',
      preservePlaybackPhase: true,
      automationIntent: {
        gain: 'increase smoothly',
        frequency: 'restore high frequencies smoothly',
        spatialWidth: 'widen smoothly',
        reverb: 'reduce enclosed reflections smoothly',
      },
    }],
    ambienceSources: [{
      sourceId: 'rain-bed',
      sourceContinuityId: 'storm-rain',
      worldId: 'stadium-world',
      role: 'bed',
      playbackType: 'seamless_loop',
      semanticRole: 'continuous storm rain bed',
      range: { startFrame: 0, endFrameExclusive: 240 },
      description: 'one continuous rain source across interior and exterior',
      generationPrompt: 'Seamless loopable steady rain ambience, neutral perspective, no foreground actions, no music.',
      promptInfluence: 0.7,
      loopPolicy: {
        enabled: true,
        candidateCount: 2,
        targetFrames: 216,
        crossfadeFrames: 12,
        phaseOffsetFrames: 0,
        promptInfluence: 0.7,
      },
    }],
    scoreCues: [{
      cueId: 'score-master',
      musicalContinuityId: 'score-continuity',
      range: { startFrame: 0, endFrameExclusive: 240 },
      narrativeDiagnosis: {
        surfaceEmotion: 'internal story diagnosis',
        trueScoringEmotion: 'controlled pressure',
        scoringStance: 'procedural_control',
        avoidEmotions: ['melodrama'],
        musicShouldDo: 'remain continuous and restrained',
        musicShouldNotDo: 'imitate literal action sounds',
      },
      musicTheorySpec: {
        version: 3,
        bpm: 60,
        meter: '4/4',
        form: 'through_composed',
        metricSalience: 'suppressed',
        eventSpacing: 'asynchronous',
        pitch: {
          centerType: 'weakened_pitch_field',
          centerPitch: 'D',
          collection: 'chromatic_saturation',
          intervalRelations: ['minor_second_aggregation', 'tritone_polarity'],
          microtonality: 'limited',
        },
        harmony: {
          functionalSyntax: 'prohibited',
          cadencePolicy: 'no_cadence',
          harmonicRhythm: 'extremely_slow',
        },
        voiceLeading: ['incremental_micro_motion', 'semitone_displacement'],
        texture: {
          organization: 'independent_sustained_layers',
          density: 'sparse',
          layerIndependence: 0.8,
        },
        spectrum: {
          foundation: ['sub', 'low'],
          upperActivity: 'isolated_partials',
          evolution: 'continuous_redistribution',
        },
        ensembleComplexity: 'chamber',
        spectralBudget: { sub: 12, low: 20, lowMid: 20, mid: 20, highMid: 12, high: 10, air: 6 },
        renderStrategies: ['balanced_ensemble', 'counterpoint_clarity', 'spectral_depth', 'microdynamic_detail'],
        orchestration: [{
          partId: 'synth-foundation',
          family: 'synthesizer',
          instrument: 'filtered_analog_synthesizer',
          register: 'low',
          spectralSlot: 'low',
          role: 'foundation',
          techniques: ['sustained_tone'],
          rhythmicFunction: 'sustained_field',
          spatial: { pan: 0, width: 0.8, reverbSend: 0.35 },
          phaseStates: [{ phaseId: 'full-cue', presence: 'active', density: 0.6, energy: 0.3 }],
        }, {
          partId: 'bass-clarinet-partial',
          family: 'woodwinds',
          instrument: 'bass_clarinet',
          register: 'low_mid',
          spectralSlot: 'low_mid',
          role: 'partial',
          techniques: ['air_noise'],
          rhythmicFunction: 'asynchronous_texture',
          spatial: { pan: -0.3, width: 0.35, reverbSend: 0.5 },
          phaseStates: [{ phaseId: 'full-cue', presence: 'active', density: 0.25, energy: 0.2 }],
        }, {
          partId: 'prepared-piano-resonance',
          family: 'keyboards',
          instrument: 'prepared_piano',
          register: 'mid',
          spectralSlot: 'mid',
          role: 'resonance',
          techniques: ['sympathetic_resonance'],
          rhythmicFunction: 'slow_pulse',
          spatial: { pan: 0.25, width: 0.45, reverbSend: 0.4 },
          phaseStates: [{ phaseId: 'full-cue', presence: 'active', density: 0.2, energy: 0.2 }],
        }, {
          partId: 'string-harmonic-air',
          family: 'strings',
          instrument: 'string_harmonics',
          register: 'high',
          spectralSlot: 'air',
          role: 'partial',
          techniques: ['harmonic_fingering'],
          rhythmicFunction: 'counterline',
          spatial: { pan: 0.4, width: 0.65, reverbSend: 0.6 },
          phaseStates: [{ phaseId: 'full-cue', presence: 'active', density: 0.15, energy: 0.15 }],
        }],
        relationships: [{
          firstPartId: 'synth-foundation', secondPartId: 'bass-clarinet-partial',
          relation: 'spectral_support', collisionPolicy: 'separate_registers',
        }, {
          firstPartId: 'bass-clarinet-partial', secondPartId: 'prepared-piano-resonance',
          relation: 'call_response', collisionPolicy: 'alternate_attacks',
        }, {
          firstPartId: 'prepared-piano-resonance', secondPartId: 'string-harmonic-air',
          relation: 'independent', collisionPolicy: 'dynamic_priority_first',
        }],
        dynamics: {
          envelope: 'long_arc',
          transientPolicy: 'suppressed',
          minimumEnergy: 0.15,
          maximumEnergy: 0.45,
        },
        phases: [{
          phaseId: 'full-cue',
          range: { startFrame: 0, endFrameExclusive: 240 },
          function: 'transform',
          energy: 0.3,
          density: 'sparse',
          spectralBand: 'low',
          transientDensity: 0.05,
        }],
        prohibitions: [
          'vocals',
          'lyrics',
          'spoken_word',
          'literal_sound_effects',
          'environmental_recordings',
          'functional_dominant_tonic',
          'authentic_cadence',
          'heroic_brass',
          'triumphant_rhythm',
          'romantic_swell',
          'cathartic_climax',
          'trailer_impacts',
          'stable_groove',
          'periodic_phrase_cycle',
        ],
      },
      intentionalSilenceRanges: [],
    }],
    automationLanes: [],
  }
}

export function createTestTimeline(): AudioTimelineV2 {
  const plan = createTestContinuityPlan()
  return {
    ...plan,
    timelineSignature: 'test-signature',
    clock: TEST_CLOCK,
    nativeAudioPolicy: {
      provider: 'video_model_native',
      dialogueAndActionPolicy: 'keep_native_dialogue_and_synchronized_actions',
      generatedPostRoles: ['ambience', 'bgm'],
      missingCriticalActionPolicy: 'fail_and_regenerate_video_segment',
    },
    clips: [{
      order: 1,
      sourceKind: 'panel',
      panelId: 'panel-1',
      groupId: null,
      shotNumber: 1,
      shotNumbers: [1],
      range: { startFrame: 0, endFrameExclusive: 240 },
      visualSummary: 'stadium sequence',
      soundDirection: 'native dialogue and synchronized actions only',
    }],
    nativeActionEvents: [],
    stemPlan: [{
      role: 'native_video',
      status: 'generated',
      provider: null,
      modelId: null,
      modelKey: null,
      generationKind: 'native_reference',
      description: 'native',
    }, {
      role: 'ambience',
      status: 'planned',
      provider: 'elevenlabs',
      modelId: 'eleven_text_to_sound_v2',
      modelKey: 'elevenlabs::eleven_text_to_sound_v2',
      generationKind: 'ambience',
      description: 'ambience',
    }, {
      role: 'bgm',
      status: 'planned',
      provider: 'fal',
      modelId: 'fal-ai/lyria3/pro',
      modelKey: 'fal::fal-ai/lyria3/pro',
      generationKind: 'music',
      description: 'score',
    }],
  }
}
