import type { AudioContinuityPlan, AudioTimelineV2, TimelineClock } from '@/lib/audio-design/types'

export const TEST_CLOCK: TimelineClock = {
  fpsNumerator: 24,
  fpsDenominator: 1,
  sampleRate: 48_000,
  totalFrames: 240,
}

export function createTestContinuityPlan(): AudioContinuityPlan {
  return {
    schemaVersion: 2,
    soundWorlds: [{
      worldId: 'stadium-world',
      continuityKey: 'stadium-same-night-same-storm',
      range: { startFrame: 0, endFrameExclusive: 240 },
      location: 'indoor stadium and its exterior entrance',
      timeContext: 'same night',
      weatherContext: 'same rainstorm',
      persistentSourceIds: ['stadium-crowd', 'storm-rain'],
      perspectives: [{
        perspectiveId: 'stadium-interior',
        zoneId: 'interior',
        range: { startFrame: 0, endFrameExclusive: 120 },
        enclosure: 'enclosed',
        distance: 'far',
        occlusion: 0.7,
        description: 'rain filtered by the stadium shell',
      }, {
        perspectiveId: 'stadium-exterior',
        zoneId: 'exterior',
        range: { startFrame: 120, endFrameExclusive: 240 },
        enclosure: 'open',
        distance: 'near',
        occlusion: 0.1,
        description: 'the same storm heard directly outdoors',
      }],
    }],
    acousticTransitions: [{
      transitionId: 'exit-stadium',
      sourceContinuityId: 'storm-rain',
      range: { startFrame: 108, endFrameExclusive: 132 },
      fromZoneId: 'interior',
      toZoneId: 'exterior',
      transitionType: 'exiting_enclosure',
      preservePlaybackPhase: true,
      automationIntent: {
        gain: 'increase smoothly',
        frequency: 'restore high frequencies smoothly',
        spatialWidth: 'widen smoothly',
        reverb: 'reduce enclosed reflections smoothly',
      },
    }],
    ambienceSources: [{
      sourceId: 'rain-bed',
      sourceContinuityId: 'storm-rain',
      worldId: 'stadium-world',
      playbackType: 'seamless_loop',
      semanticRole: 'continuous storm rain bed',
      range: { startFrame: 0, endFrameExclusive: 240 },
      description: 'one continuous rain source across interior and exterior',
      generationPrompt: 'Seamless loopable steady rain ambience, neutral perspective, no foreground actions, no music.',
      promptInfluence: 0.7,
      loopPolicy: {
        enabled: true,
        candidateCount: 2,
        targetFrames: 216,
        crossfadeFrames: 12,
        phaseOffsetFrames: 0,
        promptInfluence: 0.7,
      },
    }],
    scoreCues: [{
      cueId: 'score-master',
      musicalContinuityId: 'score-continuity',
      range: { startFrame: 0, endFrameExclusive: 240 },
      narrativeDiagnosis: {
        surfaceEmotion: 'internal story diagnosis',
        trueScoringEmotion: 'controlled pressure',
        scoringStance: 'procedural_control',
        avoidEmotions: ['melodrama'],
        musicShouldDo: 'remain continuous and restrained',
        musicShouldNotDo: 'imitate literal action sounds',
      },
      generationSpec: {
        bpm: 60,
        key: 'D minor',
        meter: '4/4',
        style: 'minimalist_underscore',
        emotionalProfile: 'cold_procedural_tension',
        harmonicLanguage: 'sparse_unresolved_minor',
        density: 'sparse',
        registers: ['low', 'low_mid'],
        instruments: ['muted_analog_synthesizer', 'soft_sub_bass'],
        articulations: ['sustained', 'soft_attack'],
        sections: [{
          sectionId: 'full-cue',
          range: { startFrame: 0, endFrameExclusive: 240 },
          function: 'development',
          energy: 0.3,
          density: 'sparse',
          harmonicTension: 0.4,
          instruments: ['muted_analog_synthesizer'],
          articulations: ['sustained'],
        }],
      },
      intentionalSilenceRanges: [],
    }],
    automationLanes: [{
      laneId: 'rain-perspective-gain',
      targetBus: 'ambience',
      targetSourceId: 'rain-bed',
      parameter: 'gain_db',
      keyframes: [
        { frame: 108, value: -8, interpolation: 'smooth' },
        { frame: 132, value: -2, interpolation: 'smooth' },
      ],
      postBehavior: 'hold',
      reason: 'same rain source moves from interior to exterior perspective',
      sourceEventId: 'exit-stadium',
    }],
  }
}

export function createTestTimeline(): AudioTimelineV2 {
  const plan = createTestContinuityPlan()
  return {
    ...plan,
    timelineSignature: 'test-signature',
    clock: TEST_CLOCK,
    nativeAudioPolicy: {
      provider: 'video_model_native',
      dialogueAndActionPolicy: 'keep_native_dialogue_and_synchronized_actions',
      generatedPostRoles: ['ambience', 'bgm'],
      missingCriticalActionPolicy: 'fail_and_regenerate_video_segment',
    },
    clips: [{
      order: 1,
      sourceKind: 'panel',
      panelId: 'panel-1',
      groupId: null,
      shotNumber: 1,
      shotNumbers: [1],
      range: { startFrame: 0, endFrameExclusive: 240 },
      visualSummary: 'stadium sequence',
      soundDirection: 'native dialogue and synchronized actions only',
    }],
    nativeActionEvents: [],
    stemPlan: [{
      role: 'native_video',
      status: 'generated',
      provider: null,
      modelId: null,
      modelKey: null,
      generationKind: 'native_reference',
      description: 'native',
    }, {
      role: 'ambience',
      status: 'planned',
      provider: 'elevenlabs',
      modelId: 'eleven_text_to_sound_v2',
      modelKey: 'elevenlabs::eleven_text_to_sound_v2',
      generationKind: 'ambience',
      description: 'ambience',
    }, {
      role: 'bgm',
      status: 'planned',
      provider: 'fal',
      modelId: 'fal-ai/lyria3/pro',
      modelKey: 'fal::fal-ai/lyria3/pro',
      generationKind: 'music',
      description: 'score',
    }],
  }
}
